import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbars/Navbar";


const Gotham = localFont({
  src: [
    {
      path: '../../public/fonts/Gotham-Thin.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gotham-ExtraLight.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gotham-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gotham-Book.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GOTHAM-BOLD.otf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GothamNarrow-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-gotham',
})

export const metadata = {
  title: "Stereo Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Gotham.variable} antialiased font-gotham`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}